# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6e0e0482b5be10155c2545f3f8101ada858c5829177d40e6eaa01888500cc233507bd70f6a867635313d8d27052a1fa2c4d1298baed290596a0d18887113ee

test:
  secret_key_base: fa65ff60236f228c9ace51020bdafaee745be232815aba72e816b8e98291398e158c3c93e16001cbb6a41f49ac5c25055e2b267e4c210f52aaa420d21be766cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
